# Generated by Django 5.1.3 on 2025-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Выберите изображение для новости', upload_to='news/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Введите заголовок новости на русском языке (до 255 символов)', max_length=255, verbose_name='Заголовок (RU)')),
                ('content', models.TextField(help_text='Введите текст новости на русском языке', verbose_name='Содержимое (RU)')),
                ('title_en', models.CharField(blank=True, help_text='Автоматически переводится с русского на английский', max_length=255, null=True, verbose_name='Заголовок (EN)')),
                ('content_en', models.TextField(blank=True, help_text='Автоматически переводится с русского на английский', null=True, verbose_name='Содержимое (EN)')),
                ('title_ky', models.CharField(blank=True, help_text='Автоматически переводится с русского на кыргызский', max_length=255, null=True, verbose_name='Заголовок (Kyrgyz)')),
                ('content_ky', models.TextField(blank=True, help_text='Автоматически переводится с русского на кыргызский', null=True, verbose_name='Содержимое (Kyrgyz)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
