# Generated by Django 5.1.3 on 2025-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Выберите изображение для новости', upload_to='news/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Введите заголовок новости (до 255 символов)', max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст новости', verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
