# Generated by Django 5.1.3 on 2025-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Введите ваше имя для обращения', max_length=100, verbose_name='Как к вам обращаться?')),
                ('phone_number', models.CharField(help_text='Введите номер в формате +996XXXXXXXXX', max_length=20, verbose_name='Номер телефона')),
                ('is_processed', models.BooleanField(default=False, help_text='Отметьте, если заявка была обработана', verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Контактная заявка',
                'verbose_name_plural': 'Контактные заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='contactrequ_created_0c7c03_idx'), models.Index(fields=['is_processed'], name='contactrequ_is_proc_f320fb_idx')],
            },
        ),
    ]
