# Generated by Django 5.1.3 on 2025-04-06 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории мероприятия', max_length=100, verbose_name='Название категории')),
                ('name_en', models.CharField(blank=True, help_text='Название категории на английском', max_length=100, null=True, verbose_name='Название категории (англ.)')),
                ('name_ky', models.CharField(blank=True, help_text='Название категории на кыргызском', max_length=100, null=True, verbose_name='Название категории (кырг.)')),
            ],
            options={
                'verbose_name': 'Категория мероприятий',
                'verbose_name_plural': 'Категории мероприятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для мероприятия', null=True, upload_to='events/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=200, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, help_text='Название мероприятия на английском', max_length=200, null=True, verbose_name='Название (англ.)')),
                ('title_ky', models.CharField(blank=True, help_text='Название мероприятия на кыргызском', max_length=200, null=True, verbose_name='Название (кырг.)')),
                ('description', models.TextField(help_text='Подробное описание мероприятия', verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, help_text='Описание мероприятия на английском', null=True, verbose_name='Описание (англ.)')),
                ('description_ky', models.TextField(blank=True, help_text='Описание мероприятия на кыргызском', null=True, verbose_name='Описание (кырг.)')),
                ('date', models.DateTimeField(help_text='Укажите дату и время проведения мероприятия', verbose_name='Дата и время')),
                ('location', models.CharField(help_text='Физическое место проведения (адрес или название места)', max_length=200, verbose_name='Место проведения')),
                ('location_url', models.URLField(blank=True, help_text='Ссылка на карту или страницу места проведения (необязательно)', max_length=255, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на место проведения')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если мероприятие активно и должно отображаться', verbose_name='Активно')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию мероприятия', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event.eventcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='event_event_date_3037c4_idx'), models.Index(fields=['category'], name='event_event_categor_6a4556_idx'), models.Index(fields=['is_active'], name='event_event_is_acti_692446_idx'), models.Index(fields=['is_active', '-date'], name='event_event_is_acti_8ea6cc_idx')],
            },
        ),
    ]
